version: '2'
services:
    easyconnect:
        image: hagb/docker-easyconnect:7.6.3 # latest, vncless, 7.6.3, vncless-7.6.3, 7.6.7, vncless-7.6.7
        devices:
          - /dev/dri
          - /dev/net/tun
        cap_add: 
          - NET_ADMIN
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix
          - $HOME/.Xauthority:/root/.Xauthority
          - $HOME/.ecdata:/root
        environment:
          - DISPLAY=unix$DISPLAY
          - URLWINE=1
          - TYPE=X11
#          - PASSWORD=password
#          - NODANTED=
#          - EXPASSWORD=
        ports:
          - "127.0.0.1:1081:1080"
